DROP TABLE IF EXISTS RECIPES_INGREDIENTS;
DROP TABLE IF EXISTS RECIPES_MEALS;
DROP TABLE IF EXISTS MEALS;
DROP TABLE IF EXISTS REVIEWS;
DROP TABLE IF EXISTS RECIPES;
DROP TABLE IF EXISTS INGREDIENTS;
DROP TABLE IF EXISTS MODERATORS;
DROP TABLE IF EXISTS SUBSCRIBERS;

CREATE TABLE INGREDIENTS (
	ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY, 
    NAME VARCHAR(50)
);

CREATE TABLE MODERATORS (
	ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY, 
	USERNAME VARCHAR(50) NOT NULL, 
    PASSWORD VARCHAR(256) NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    LEVEL INT NOT NULL,
    ACTIVE BOOL DEFAULT FALSE
);

CREATE TABLE RECIPES (
	ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY, 
    NAME VARCHAR(50) NOT NULL,
    LINK VARCHAR(500) NOT NULL,
    VERIFIED_BY_MODERATOR BOOL NOT NULL,
    MODERATOR_ID INT,
    TYPE VARCHAR(50) NOT NULL,
    FOREIGN KEY(MODERATOR_ID) REFERENCES MODERATORS(ID)
);

CREATE TABLE REVIEWS (
	ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY, 
    REVIEWER_NAME VARCHAR(50) NOT NULL,
    REVIEWER_EMAIL VARCHAR(100) NOT NULL,
    REVIEW VARCHAR(750) NOT NULL,
    REVIEW_DATE DATE NOT NULL,
    VERIFIED_BY_MODERATOR BOOL NOT NULL,
    RECIPE_ID INT NOT NULL,
	MODERATOR_ID INT,
    FOREIGN KEY (RECIPE_ID) REFERENCES RECIPES(ID),
    FOREIGN KEY(MODERATOR_ID) REFERENCES MODERATORS(ID)
);

CREATE TABLE RECIPES_INGREDIENTS (
	ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	RECIPE_ID INT NOT NULL,
    INGREDIENT_ID INT NOT NULL,
    FOREIGN KEY (RECIPE_ID) REFERENCES RECIPES(ID),
    FOREIGN KEY (INGREDIENT_ID) REFERENCES INGREDIENTS(ID)
);

CREATE TABLE MEALS (
	ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	NAME VARCHAR(50) NOT NULL
);

CREATE TABLE RECIPES_MEALS (
	ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	RECIPE_ID INT NOT NULL,
    MEAL_ID INT NOT NULL,
    FOREIGN KEY (RECIPE_ID) REFERENCES RECIPES(ID),
    FOREIGN KEY (MEAL_ID) REFERENCES MEALS(ID)
);

CREATE TABLE SUBSCRIBERS (
	ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY, 
	EMAIL VARCHAR(50) NOT NULL, 
    NAME VARCHAR(50) NOT NULL
);
